import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

import type { Metadata } from "next";
import "./globals.css";

import LenisScroll from "./lenis";

import { Cinzel, Amiri, Tajawal, Spectral, Cairo, Karla } from "next/font/google";
import localFont from 'next/font/local'

const cairo = Cairo({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['arabic'],
  variable: "--font-cairo",
});

const tajawal = Tajawal({
  weight: ['400', '500'],
  subsets: ['arabic'],
  variable: "--font-tajawal",
});

const amiri = Amiri({
  weight: ['400', '700'],
  subsets: ['arabic'],
  variable: "--font-amiri",
});

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-cinzel",
});

const spectral = Spectral({
  weight: ['400', '700'],
  subsets: ["latin"],
  variable: "--font-spectral",
});

const karla = Karla({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-karla",
  display: "swap",
});

const ghorab = localFont({
  src: '../fonts/ghorab.otf',
  variable: '--font-ghorab',
  display: 'swap',
})

const thuluth = localFont({
  src: '../fonts/thuluth.ttf',
  variable: '--font-thuluth',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Sera",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {

  const { locale } = await params;
  
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();
  // const dir = locale === 'ar' ? 'rtl' : 'ltr';

  return (
    <html lang={locale} suppressHydrationWarning className={`${cinzel.variable} ${karla.variable} ${ghorab.variable} ${thuluth.variable} ${spectral.variable} ${amiri.variable} ${tajawal.variable} ${cairo.variable}`}>
      <body className="overflow-x-hidden">

        <NextIntlClientProvider messages={messages}>
          <LenisScroll />
          {children}
        </NextIntlClientProvider>

      </body>
    </html>
  );
}
